#! /bin/sh

/usr/bin/start-pulseaudio-x11 && sleep 2s

xset +fp /usr/share/fonts/local &
xset +fp /usr/share/fonts/misc &
xset +fp ~/.fonts &
xset fp rehash &
fc-cache -fv &

xset s off &
xset s noblank &
xset s noexpose &
xset c on &
xset -dpms &

sxhkd &

polybar -c ~/.config/polybar/polybar.conf &

bspc config top_padding 27

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

